// @doc-schema-version: 1.0.0
import type { DocumentPatch } from "@black-bean-sprouts/doc-schema";
import type { LLMMessage, LLMProvider, LLMResponse, LLMStreamChunk } from "@black-bean-sprouts/agent-runtime";

type LLMChatOptions = Parameters<LLMProvider["chat"]>[1];

export class MockPatchLLMProvider implements LLMProvider {
  async chat(messages: LLMMessage[], _options?: LLMChatOptions): Promise<LLMResponse> {
    const lastToolMessage = [...messages].reverse().find((message) => message.role === "tool");
    if (lastToolMessage) {
      return {
        content: "Document patch applied successfully.",
        usage: { inputTokens: 1, outputTokens: 1 },
      };
    }

    const lastUserMessage = [...messages].reverse().find((message) => message.role === "user")?.content ?? "";
    return {
      content: "I will apply a document patch now.",
      toolCalls: [
        {
          id: "mock_patch_call",
          name: "patch_document",
          arguments: JSON.stringify({ patches: buildMockPatches(lastUserMessage) }),
        },
      ],
      usage: { inputTokens: 1, outputTokens: 1 },
    };
  }

  async *stream(_messages: LLMMessage[], _options?: LLMChatOptions): AsyncIterable<LLMStreamChunk> {
    yield { type: "content", content: "mock" };
  }
}

function buildMockPatches(message: string): DocumentPatch[] {
  const title = extractField(message, "title", "Mock Patch Title");
  const sectionTitle = extractField(message, "section", "Introduction");

  return [
    {
      op: "update_meta",
      meta: {
        title,
      },
    },
    {
      op: "insert_block",
      parentId: "root",
      index: 0,
      node: {
        id: `sec-${crypto.randomUUID()}`,
        type: "section",
        attrs: {
          level: 1,
          title: sectionTitle,
        },
        content: [
          {
            id: `p-${crypto.randomUUID()}`,
            type: "paragraph",
            attrs: {},
            content: [
              {
                type: "text",
                text: "This paragraph is generated by the mock kernel runtime.",
              },
            ],
          },
        ],
      },
    },
  ];
}

function extractField(message: string, key: string, fallback: string): string {
  const pattern = new RegExp(`${key}\\s*[:=]\\s*([^;\\n]+)`, "i");
  const match = pattern.exec(message);
  return match?.[1]?.trim() || fallback;
}
