export type { Doc, DocMetadata, BlockNode, ParagraphBlock, HeadingBlock, FigureBlock, TableBlock, TableRow, TableCell, FormulaBlock, ReferenceListBlock, ReferenceItem, AbstractBlock, SectionBlock, InlineNode, TextMark } from "./doc/types.js";
export { createEmptyDoc, findBlockById, findParentBlock } from "./doc/types.js";
export type { DocumentPatch, InsertBlockPatch, RemoveBlockPatch, MoveBlockPatch, ReplaceBlockPatch, UpdateMetadataPatch, InsertInlinePatch, RemoveInlinePatch, ReplaceInlinePatch, InsertTableRowPatch, RemoveTableRowPatch, ReplaceTableCellPatch, AddReferencePatch, RemoveReferencePatch, UpdateReferencePatch } from "./patch/types.js";
export type { DocumentPatchBatch, PatchSource, PatchConflictError } from "./patch/batch.js";
export { createBatch, createPatchConflictError, isPatchConflictError } from "./patch/batch.js";
export { applyBatch, applyPatch, isApplyError } from "./patch/apply.js";
export type { ApplyBatchResult, ApplyPatchResult, ApplyError } from "./patch/apply.js";
export { patchCompiler } from "./patch/compiler.js";
export type { PatchIntent, PatchCompiler } from "./patch/compiler.js";
export { isValidDoc } from "./validate.js";
export type { ValidationResult } from "./validate.js";
